package ctrlflow.except.howTo.whatIs

/**
 * Exercise: Cause an exception
 * https://hyperskill.org/learn/step/7247
 * @author JetBrains Academy
 * Solution by Lo√Øc Baillif
 */

fun exercise1() {
    println("*** Exercise: Cause an exception ***")

    val userAge = "e".toInt()

    println("\n*** End of exercise ***")
}